name: test1
on:
  push:

jobs:
  say-Hello:
    runs-on: ubuntu-latest
    steps:
      - name: show file tree before checkout
        run: ls -la

      - name: checkout code
        uses: actions/checkout@v4

      - name: show file tree after checkout
        run: ls -la
