name: test1
on:
  push:

jobs:
  golang-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'

      - name: go mod download
        run: go mod download

      - name: print env info
        run: |
          go env
          go version

      - name: run test
        run: go test -v ./...

  test-demo:
    runs-on: ubuntu-latest
    steps:
      - name: print file tree
        run: ls -Fa
